name: Shelter SDK Tests

on:
  push:
    branches: [main]
    paths:
      - "sdk/**"
  pull_request:
    branches: [main]
    paths:
      - "sdk/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Shelter SDK Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23.11.0"
          cache: "npm"
          cache-dependency-path: "./sdk/package-lock.json"

      - name: Install dependencies
        working-directory: ./sdk
        run: npm ci

      - name: Build
        working-directory: ./sdk
        run: npm run build

      - name: Run tests
        working-directory: ./sdk
        run: npm run test
